<a href="https://colab.research.google.com/github/ORCT/ds-section2-project/blob/main/Data_Preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

딕셔너리 길이가 안맞아서 바로 df로 안바뀌어서 일단 txt로 저장해놨음.

그거 길이 재고 맞춰서 df로 바꾸는 거부터 시작하자고

In [1]:
import pandas as pd
data = pd.read_table('data_dict_40_100match.txt')
data

     Color맥라렌/1 : [('차이나 라사', 1, '', 'Color맥라렌', "1'50'03"), ('차이나 라사', 2, '프로토 바이크 V1', 'KR퀵서비스', "1'50'04"), ('차이나 라사', 3, '나이트 세이버 V1', '하이럼스미스', "1'50'66"), ('차이나 라사', 4, '멘티스 X', 'Color옴팡이', "1'51'98")]
0     Color맥라렌/2 : [('네모 장난감 선물공장', 1, '', 'Color맥라렌...
1     Color맥라렌/3 : [('쥐라기 공룡 결투장', 1, '', 'Color맥라렌'...
2     Color맥라렌/4 : [('차이나 라사', 1, '', 'Color맥라렌', "1...
3     Color맥라렌/5 : [('메이플 헤네시스 공원', 1, '', 'Color맥라렌...
4     Color맥라렌/6 : [('WKC 투어링 랠리', 1, '', 'Color맥라렌'...
...                                                 ...
2794  까이브/96 : [('노르테유 스카이웨이', 1, '', 'YJWP', "1'07'...
2795  까이브/97 : [('WKC 코리아 서킷', 1, '', 'YJWP', "1'07'...
2796  까이브/98 : [('메이플 리스항구 언덕길', 1, '', 'YJWP', "1'0...
2797  까이브/99 : [('월드 이탈리아 피사의 사탑', 1, '', 'YJWP', "1...
2798  까이브/100 : [('월드 두바이 다운타운', 1, '', 'YJWP', "1'0...

[2799 rows x 1 columns]

In [2]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2799 entries, 0 to 2798
Data columns (total 1 columns):
 #   Column                                                                                                                                                                                                      Non-Null Count  Dtype
---  ------                                                                                                                                                                                                      --------------  -----
 0   Color맥라렌/1 : [('차이나 라사', 1, '', 'Color맥라렌', "1'50'03"), ('차이나 라사', 2, '프로토 바이크 V1', 'KR퀵서비스', "1'50'04"), ('차이나 라사', 3, '나이트 세이버 V1', '하이럼스미스', "1'50'66"), ('차이나 라사', 4, '멘티스 X', 'Color옴팡이', "1'51'98")]  2799 non-null   object
dtypes: object(1)
memory usage: 22.0+ KB

In [3]:
index = pd.Series(range(1, 2800))
data.set_index(keys=[index],inplace=True)
data

     Color맥라렌/1 : [('차이나 라사', 1, '', 'Color맥라렌', "1'50'03"), ('차이나 라사', 2, '프로토 바이크 V1', 'KR퀵서비스', "1'50'04"), ('차이나 라사', 3, '나이트 세이버 V1', '하이럼스미스', "1'50'66"), ('차이나 라사', 4, '멘티스 X', 'Color옴팡이', "1'51'98")]
1     Color맥라렌/2 : [('네모 장난감 선물공장', 1, '', 'Color맥라렌...
2     Color맥라렌/3 : [('쥐라기 공룡 결투장', 1, '', 'Color맥라렌'...
3     Color맥라렌/4 : [('차이나 라사', 1, '', 'Color맥라렌', "1...
4     Color맥라렌/5 : [('메이플 헤네시스 공원', 1, '', 'Color맥라렌...
5     Color맥라렌/6 : [('WKC 투어링 랠리', 1, '', 'Color맥라렌'...
...                                                 ...
2795  까이브/96 : [('노르테유 스카이웨이', 1, '', 'YJWP', "1'07'...
2796  까이브/97 : [('WKC 코리아 서킷', 1, '', 'YJWP', "1'07'...
2797  까이브/98 : [('메이플 리스항구 언덕길', 1, '', 'YJWP', "1'0...
2798  까이브/99 : [('월드 이탈리아 피사의 사탑', 1, '', 'YJWP', "1...
2799  까이브/100 : [('월드 두바이 다운타운', 1, '', 'YJWP', "1'0...

[2799 rows x 1 columns]

In [4]:
df = pd.DataFrame({'origin_dict':[0]})
df.loc[0,:] = data.columns
data.columns = ['origin_dict']
df = df.append(data,ignore_index=True)

이제 쟤들 값 바꿔야해

맨 앞에 있는게 매치id(내가 임의로 부여함)니까 ' : ' 이거 기준으로 스플릿해서 쓰면 되지 않을까

In [5]:
df['Match_Id'], df['Match_Data'] = df['origin_dict'].str.split(' : ').str
df

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: Columnar iteration over characters will be deprecated in future releases.
  """Entry point for launching an IPython kernel.

,origin_dict,Match_Id,Match_Data
0,"Color맥라렌/1 : [('차이나 라사', 1, '', 'Color맥라렌', ""1...",Color맥라렌/1,"[('차이나 라사', 1, '', 'Color맥라렌', ""1'50'03""), ('차..."
1,"Color맥라렌/2 : [('네모 장난감 선물공장', 1, '', 'Color맥라렌...",Color맥라렌/2,"[('네모 장난감 선물공장', 1, '', 'Color맥라렌', ""1'50'03"")..."
2,"Color맥라렌/3 : [('쥐라기 공룡 결투장', 1, '', 'Color맥라렌'...",Color맥라렌/3,"[('쥐라기 공룡 결투장', 1, '', 'Color맥라렌', ""1'50'03""),..."
3,"Color맥라렌/4 : [('차이나 라사', 1, '', 'Color맥라렌', ""1...",Color맥라렌/4,"[('차이나 라사', 1, '', 'Color맥라렌', ""1'50'03""), ('차..."
4,"Color맥라렌/5 : [('메이플 헤네시스 공원', 1, '', 'Color맥라렌...",Color맥라렌/5,"[('메이플 헤네시스 공원', 1, '', 'Color맥라렌', ""1'50'03"")..."
...,...,...,...
2795,"까이브/96 : [('노르테유 스카이웨이', 1, '', 'YJWP', ""1'07'...",까이브/96,"[('노르테유 스카이웨이', 1, '', 'YJWP', ""1'07'20""), ('노..."
2796,"까이브/97 : [('WKC 코리아 서킷', 1, '', 'YJWP', ""1'07'...",까이브/97,"[('WKC 코리아 서킷', 1, '', 'YJWP', ""1'07'20""), ('W..."
2797,"까이브/98 : [('메이플 리스항구 언덕길', 1, '', 'YJWP', ""1'0...",까이브/98,"[('메이플 리스항구 언덕길', 1, '', 'YJWP', ""1'07'20""), (..."
2798,"까이브/99 : [('월드 이탈리아 피사의 사탑', 1, '', 'YJWP', ""1...",까이브/99,"[('월드 이탈리아 피사의 사탑', 1, '', 'YJWP', ""1'07'20""),..."
2799,"까이브/100 : [('월드 두바이 다운타운', 1, '', 'YJWP', ""1'0...",까이브/100,"[('월드 두바이 다운타운', 1, '', 'YJWP', ""1'07'20""), ('..."

괄호 사이에 있는 값들을 어떻게 해야 안떨어트리고 분리할 수 있을까

전부 쉼표라서 데이터에 \가 다들어가있다(자동으로 ' 이거 안떨어트리도록 삽입되나봄)

In [6]:
df['Match_User_1'], df['Match_User_2'], df['Match_User_3'], df['Match_User_4'] = 0, 0, 0, 0
for i in range(0,2800):
  tmp = df.loc[i,'Match_Data'].split('), ')
  for j in range(len(tmp)):
    df.loc[i, f'Match_User_{j+1}'] = tmp[j]
# df['Match_User'] = df['Match_Data'].str.split('), ')
# df.loc[0,'Match_Data'].split('), ')
df

,origin_dict,Match_Id,Match_Data,Match_User_1,Match_User_2,Match_User_3,Match_User_4
0,"Color맥라렌/1 : [('차이나 라사', 1, '', 'Color맥라렌', ""1...",Color맥라렌/1,"[('차이나 라사', 1, '', 'Color맥라렌', ""1'50'03""), ('차...","[('차이나 라사', 1, '', 'Color맥라렌', ""1'50'03""","('차이나 라사', 2, '프로토 바이크 V1', 'KR퀵서비스', ""1'50'04""","('차이나 라사', 3, '나이트 세이버 V1', '하이럼스미스', ""1'50'66""","('차이나 라사', 4, '멘티스 X', 'Color옴팡이', ""1'51'98"")]"
1,"Color맥라렌/2 : [('네모 장난감 선물공장', 1, '', 'Color맥라렌...",Color맥라렌/2,"[('네모 장난감 선물공장', 1, '', 'Color맥라렌', ""1'50'03"")...","[('네모 장난감 선물공장', 1, '', 'Color맥라렌', ""1'50'03""","('네모 장난감 선물공장', 2, '프로토 바이크 V1', 'KR퀵서비스', ""1'...","('네모 장난감 선물공장', 3, '나이트 세이버 V1', '하이럼스미스', ""1'...","('네모 장난감 선물공장', 4, '멘티스 X', 'Color옴팡이', ""1'51'..."
2,"Color맥라렌/3 : [('쥐라기 공룡 결투장', 1, '', 'Color맥라렌'...",Color맥라렌/3,"[('쥐라기 공룡 결투장', 1, '', 'Color맥라렌', ""1'50'03""),...","[('쥐라기 공룡 결투장', 1, '', 'Color맥라렌', ""1'50'03""","('쥐라기 공룡 결투장', 2, '프로토 바이크 V1', 'KR퀵서비스', ""1'5...","('쥐라기 공룡 결투장', 3, '나이트 세이버 V1', '하이럼스미스', ""1'5...","('쥐라기 공룡 결투장', 4, '멘티스 X', 'Color옴팡이', ""1'51'9..."
3,"Color맥라렌/4 : [('차이나 라사', 1, '', 'Color맥라렌', ""1...",Color맥라렌/4,"[('차이나 라사', 1, '', 'Color맥라렌', ""1'50'03""), ('차...","[('차이나 라사', 1, '', 'Color맥라렌', ""1'50'03""","('차이나 라사', 2, '프로토 바이크 V1', 'KR퀵서비스', ""1'50'04""","('차이나 라사', 3, '나이트 세이버 V1', '하이럼스미스', ""1'50'66""","('차이나 라사', 4, '멘티스 X', 'Color옴팡이', ""1'51'98"")]"
4,"Color맥라렌/5 : [('메이플 헤네시스 공원', 1, '', 'Color맥라렌...",Color맥라렌/5,"[('메이플 헤네시스 공원', 1, '', 'Color맥라렌', ""1'50'03"")...","[('메이플 헤네시스 공원', 1, '', 'Color맥라렌', ""1'50'03""","('메이플 헤네시스 공원', 2, '프로토 바이크 V1', 'KR퀵서비스', ""1'...","('메이플 헤네시스 공원', 3, '나이트 세이버 V1', '하이럼스미스', ""1'...","('메이플 헤네시스 공원', 4, '멘티스 X', 'Color옴팡이', ""1'51'..."
...,...,...,...,...,...,...,...
2795,"까이브/96 : [('노르테유 스카이웨이', 1, '', 'YJWP', ""1'07'...",까이브/96,"[('노르테유 스카이웨이', 1, '', 'YJWP', ""1'07'20""), ('노...","[('노르테유 스카이웨이', 1, '', 'YJWP', ""1'07'20""","('노르테유 스카이웨이', 2, '스펙터 V1', '뱩소현', ""1'07'25""","('노르테유 스카이웨이', 3, '', '까이브', ""1'09'02""","('노르테유 스카이웨이', 4, '', 'l지존지후l', ""1'09'49"")]"
2796,"까이브/97 : [('WKC 코리아 서킷', 1, '', 'YJWP', ""1'07'...",까이브/97,"[('WKC 코리아 서킷', 1, '', 'YJWP', ""1'07'20""), ('W...","[('WKC 코리아 서킷', 1, '', 'YJWP', ""1'07'20""","('WKC 코리아 서킷', 2, '스펙터 V1', '뱩소현', ""1'07'25""","('WKC 코리아 서킷', 3, '', '까이브', ""1'09'02""","('WKC 코리아 서킷', 4, '', 'l지존지후l', ""1'09'49"")]"
2797,"까이브/98 : [('메이플 리스항구 언덕길', 1, '', 'YJWP', ""1'0...",까이브/98,"[('메이플 리스항구 언덕길', 1, '', 'YJWP', ""1'07'20""), (...","[('메이플 리스항구 언덕길', 1, '', 'YJWP', ""1'07'20""","('메이플 리스항구 언덕길', 2, '스펙터 V1', '뱩소현', ""1'07'25""","('메이플 리스항구 언덕길', 3, '', '까이브', ""1'09'02""","('메이플 리스항구 언덕길', 4, '', 'l지존지후l', ""1'09'49"")]"
2798,"까이브/99 : [('월드 이탈리아 피사의 사탑', 1, '', 'YJWP', ""1...",까이브/99,"[('월드 이탈리아 피사의 사탑', 1, '', 'YJWP', ""1'07'20""),...","[('월드 이탈리아 피사의 사탑', 1, '', 'YJWP', ""1'07'20""","('월드 이탈리아 피사의 사탑', 2, '스펙터 V1', '뱩소현', ""1'07'25""","('월드 이탈리아 피사의 사탑', 3, '', '까이브', ""1'09'02""","('월드 이탈리아 피사의 사탑', 4, '', 'l지존지후l', ""1'09'49"")]"
2799,"까이브/100 : [('월드 두바이 다운타운', 1, '', 'YJWP', ""1'0...",까이브/100,"[('월드 두바이 다운타운', 1, '', 'YJWP', ""1'07'20""), ('...","[('월드 두바이 다운타운', 1, '', 'YJWP', ""1'07'20""","('월드 두바이 다운타운', 2, '스펙터 V1', '뱩소현', ""1'07'25""","('월드 두바이 다운타운', 3, '', '까이브', ""1'09'02""","('월드 두바이 다운타운', 4, '', 'l지존지후l', ""1'09'49"")]"

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2800 entries, 0 to 2799
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   origin_dict   2800 non-null   object
 1   Match_Id      2800 non-null   object
 2   Match_Data    2800 non-null   object
 3   Match_User_1  2800 non-null   object
 4   Match_User_2  2800 non-null   object
 5   Match_User_3  2800 non-null   object
 6   Match_User_4  2800 non-null   object
dtypes: object(7)
memory usage: 153.2+ KB

In [8]:
df['Track'] = df['Match_User_1'].str.split(',').str[0]
df

,origin_dict,Match_Id,Match_Data,Match_User_1,Match_User_2,Match_User_3,Match_User_4,Track
0,"Color맥라렌/1 : [('차이나 라사', 1, '', 'Color맥라렌', ""1...",Color맥라렌/1,"[('차이나 라사', 1, '', 'Color맥라렌', ""1'50'03""), ('차...","[('차이나 라사', 1, '', 'Color맥라렌', ""1'50'03""","('차이나 라사', 2, '프로토 바이크 V1', 'KR퀵서비스', ""1'50'04""","('차이나 라사', 3, '나이트 세이버 V1', '하이럼스미스', ""1'50'66""","('차이나 라사', 4, '멘티스 X', 'Color옴팡이', ""1'51'98"")]",[('차이나 라사'
1,"Color맥라렌/2 : [('네모 장난감 선물공장', 1, '', 'Color맥라렌...",Color맥라렌/2,"[('네모 장난감 선물공장', 1, '', 'Color맥라렌', ""1'50'03"")...","[('네모 장난감 선물공장', 1, '', 'Color맥라렌', ""1'50'03""","('네모 장난감 선물공장', 2, '프로토 바이크 V1', 'KR퀵서비스', ""1'...","('네모 장난감 선물공장', 3, '나이트 세이버 V1', '하이럼스미스', ""1'...","('네모 장난감 선물공장', 4, '멘티스 X', 'Color옴팡이', ""1'51'...",[('네모 장난감 선물공장'
2,"Color맥라렌/3 : [('쥐라기 공룡 결투장', 1, '', 'Color맥라렌'...",Color맥라렌/3,"[('쥐라기 공룡 결투장', 1, '', 'Color맥라렌', ""1'50'03""),...","[('쥐라기 공룡 결투장', 1, '', 'Color맥라렌', ""1'50'03""","('쥐라기 공룡 결투장', 2, '프로토 바이크 V1', 'KR퀵서비스', ""1'5...","('쥐라기 공룡 결투장', 3, '나이트 세이버 V1', '하이럼스미스', ""1'5...","('쥐라기 공룡 결투장', 4, '멘티스 X', 'Color옴팡이', ""1'51'9...",[('쥐라기 공룡 결투장'
3,"Color맥라렌/4 : [('차이나 라사', 1, '', 'Color맥라렌', ""1...",Color맥라렌/4,"[('차이나 라사', 1, '', 'Color맥라렌', ""1'50'03""), ('차...","[('차이나 라사', 1, '', 'Color맥라렌', ""1'50'03""","('차이나 라사', 2, '프로토 바이크 V1', 'KR퀵서비스', ""1'50'04""","('차이나 라사', 3, '나이트 세이버 V1', '하이럼스미스', ""1'50'66""","('차이나 라사', 4, '멘티스 X', 'Color옴팡이', ""1'51'98"")]",[('차이나 라사'
4,"Color맥라렌/5 : [('메이플 헤네시스 공원', 1, '', 'Color맥라렌...",Color맥라렌/5,"[('메이플 헤네시스 공원', 1, '', 'Color맥라렌', ""1'50'03"")...","[('메이플 헤네시스 공원', 1, '', 'Color맥라렌', ""1'50'03""","('메이플 헤네시스 공원', 2, '프로토 바이크 V1', 'KR퀵서비스', ""1'...","('메이플 헤네시스 공원', 3, '나이트 세이버 V1', '하이럼스미스', ""1'...","('메이플 헤네시스 공원', 4, '멘티스 X', 'Color옴팡이', ""1'51'...",[('메이플 헤네시스 공원'
...,...,...,...,...,...,...,...,...
2795,"까이브/96 : [('노르테유 스카이웨이', 1, '', 'YJWP', ""1'07'...",까이브/96,"[('노르테유 스카이웨이', 1, '', 'YJWP', ""1'07'20""), ('노...","[('노르테유 스카이웨이', 1, '', 'YJWP', ""1'07'20""","('노르테유 스카이웨이', 2, '스펙터 V1', '뱩소현', ""1'07'25""","('노르테유 스카이웨이', 3, '', '까이브', ""1'09'02""","('노르테유 스카이웨이', 4, '', 'l지존지후l', ""1'09'49"")]",[('노르테유 스카이웨이'
2796,"까이브/97 : [('WKC 코리아 서킷', 1, '', 'YJWP', ""1'07'...",까이브/97,"[('WKC 코리아 서킷', 1, '', 'YJWP', ""1'07'20""), ('W...","[('WKC 코리아 서킷', 1, '', 'YJWP', ""1'07'20""","('WKC 코리아 서킷', 2, '스펙터 V1', '뱩소현', ""1'07'25""","('WKC 코리아 서킷', 3, '', '까이브', ""1'09'02""","('WKC 코리아 서킷', 4, '', 'l지존지후l', ""1'09'49"")]",[('WKC 코리아 서킷'
2797,"까이브/98 : [('메이플 리스항구 언덕길', 1, '', 'YJWP', ""1'0...",까이브/98,"[('메이플 리스항구 언덕길', 1, '', 'YJWP', ""1'07'20""), (...","[('메이플 리스항구 언덕길', 1, '', 'YJWP', ""1'07'20""","('메이플 리스항구 언덕길', 2, '스펙터 V1', '뱩소현', ""1'07'25""","('메이플 리스항구 언덕길', 3, '', '까이브', ""1'09'02""","('메이플 리스항구 언덕길', 4, '', 'l지존지후l', ""1'09'49"")]",[('메이플 리스항구 언덕길'
2798,"까이브/99 : [('월드 이탈리아 피사의 사탑', 1, '', 'YJWP', ""1...",까이브/99,"[('월드 이탈리아 피사의 사탑', 1, '', 'YJWP', ""1'07'20""),...","[('월드 이탈리아 피사의 사탑', 1, '', 'YJWP', ""1'07'20""","('월드 이탈리아 피사의 사탑', 2, '스펙터 V1', '뱩소현', ""1'07'25""","('월드 이탈리아 피사의 사탑', 3, '', '까이브', ""1'09'02""","('월드 이탈리아 피사의 사탑', 4, '', 'l지존지후l', ""1'09'49"")]",[('월드 이탈리아 피사의 사탑'
2799,"까이브/100 : [('월드 두바이 다운타운', 1, '', 'YJWP', ""1'0...",까이브/100,"[('월드 두바이 다운타운', 1, '', 'YJWP', ""1'07'20""), ('...","[('월드 두바이 다운타운', 1, '', 'YJWP', ""1'07'20""","('월드 두바이 다운타운', 2, '스펙터 V1', '뱩소현', ""1'07'25""","('월드 두바이 다운타운', 3, '', '까이브', ""1'09'02""","('월드 두바이 다운타운', 4, '', 'l지존지후l', ""1'09'49"")]",[('월드 두바이 다운타운'

In [9]:
df['Track'] = df['Track'].str.split('\'').str[1]
df

,origin_dict,Match_Id,Match_Data,Match_User_1,Match_User_2,Match_User_3,Match_User_4,Track
0,"Color맥라렌/1 : [('차이나 라사', 1, '', 'Color맥라렌', ""1...",Color맥라렌/1,"[('차이나 라사', 1, '', 'Color맥라렌', ""1'50'03""), ('차...","[('차이나 라사', 1, '', 'Color맥라렌', ""1'50'03""","('차이나 라사', 2, '프로토 바이크 V1', 'KR퀵서비스', ""1'50'04""","('차이나 라사', 3, '나이트 세이버 V1', '하이럼스미스', ""1'50'66""","('차이나 라사', 4, '멘티스 X', 'Color옴팡이', ""1'51'98"")]",차이나 라사
1,"Color맥라렌/2 : [('네모 장난감 선물공장', 1, '', 'Color맥라렌...",Color맥라렌/2,"[('네모 장난감 선물공장', 1, '', 'Color맥라렌', ""1'50'03"")...","[('네모 장난감 선물공장', 1, '', 'Color맥라렌', ""1'50'03""","('네모 장난감 선물공장', 2, '프로토 바이크 V1', 'KR퀵서비스', ""1'...","('네모 장난감 선물공장', 3, '나이트 세이버 V1', '하이럼스미스', ""1'...","('네모 장난감 선물공장', 4, '멘티스 X', 'Color옴팡이', ""1'51'...",네모 장난감 선물공장
2,"Color맥라렌/3 : [('쥐라기 공룡 결투장', 1, '', 'Color맥라렌'...",Color맥라렌/3,"[('쥐라기 공룡 결투장', 1, '', 'Color맥라렌', ""1'50'03""),...","[('쥐라기 공룡 결투장', 1, '', 'Color맥라렌', ""1'50'03""","('쥐라기 공룡 결투장', 2, '프로토 바이크 V1', 'KR퀵서비스', ""1'5...","('쥐라기 공룡 결투장', 3, '나이트 세이버 V1', '하이럼스미스', ""1'5...","('쥐라기 공룡 결투장', 4, '멘티스 X', 'Color옴팡이', ""1'51'9...",쥐라기 공룡 결투장
3,"Color맥라렌/4 : [('차이나 라사', 1, '', 'Color맥라렌', ""1...",Color맥라렌/4,"[('차이나 라사', 1, '', 'Color맥라렌', ""1'50'03""), ('차...","[('차이나 라사', 1, '', 'Color맥라렌', ""1'50'03""","('차이나 라사', 2, '프로토 바이크 V1', 'KR퀵서비스', ""1'50'04""","('차이나 라사', 3, '나이트 세이버 V1', '하이럼스미스', ""1'50'66""","('차이나 라사', 4, '멘티스 X', 'Color옴팡이', ""1'51'98"")]",차이나 라사
4,"Color맥라렌/5 : [('메이플 헤네시스 공원', 1, '', 'Color맥라렌...",Color맥라렌/5,"[('메이플 헤네시스 공원', 1, '', 'Color맥라렌', ""1'50'03"")...","[('메이플 헤네시스 공원', 1, '', 'Color맥라렌', ""1'50'03""","('메이플 헤네시스 공원', 2, '프로토 바이크 V1', 'KR퀵서비스', ""1'...","('메이플 헤네시스 공원', 3, '나이트 세이버 V1', '하이럼스미스', ""1'...","('메이플 헤네시스 공원', 4, '멘티스 X', 'Color옴팡이', ""1'51'...",메이플 헤네시스 공원
...,...,...,...,...,...,...,...,...
2795,"까이브/96 : [('노르테유 스카이웨이', 1, '', 'YJWP', ""1'07'...",까이브/96,"[('노르테유 스카이웨이', 1, '', 'YJWP', ""1'07'20""), ('노...","[('노르테유 스카이웨이', 1, '', 'YJWP', ""1'07'20""","('노르테유 스카이웨이', 2, '스펙터 V1', '뱩소현', ""1'07'25""","('노르테유 스카이웨이', 3, '', '까이브', ""1'09'02""","('노르테유 스카이웨이', 4, '', 'l지존지후l', ""1'09'49"")]",노르테유 스카이웨이
2796,"까이브/97 : [('WKC 코리아 서킷', 1, '', 'YJWP', ""1'07'...",까이브/97,"[('WKC 코리아 서킷', 1, '', 'YJWP', ""1'07'20""), ('W...","[('WKC 코리아 서킷', 1, '', 'YJWP', ""1'07'20""","('WKC 코리아 서킷', 2, '스펙터 V1', '뱩소현', ""1'07'25""","('WKC 코리아 서킷', 3, '', '까이브', ""1'09'02""","('WKC 코리아 서킷', 4, '', 'l지존지후l', ""1'09'49"")]",WKC 코리아 서킷
2797,"까이브/98 : [('메이플 리스항구 언덕길', 1, '', 'YJWP', ""1'0...",까이브/98,"[('메이플 리스항구 언덕길', 1, '', 'YJWP', ""1'07'20""), (...","[('메이플 리스항구 언덕길', 1, '', 'YJWP', ""1'07'20""","('메이플 리스항구 언덕길', 2, '스펙터 V1', '뱩소현', ""1'07'25""","('메이플 리스항구 언덕길', 3, '', '까이브', ""1'09'02""","('메이플 리스항구 언덕길', 4, '', 'l지존지후l', ""1'09'49"")]",메이플 리스항구 언덕길
2798,"까이브/99 : [('월드 이탈리아 피사의 사탑', 1, '', 'YJWP', ""1...",까이브/99,"[('월드 이탈리아 피사의 사탑', 1, '', 'YJWP', ""1'07'20""),...","[('월드 이탈리아 피사의 사탑', 1, '', 'YJWP', ""1'07'20""","('월드 이탈리아 피사의 사탑', 2, '스펙터 V1', '뱩소현', ""1'07'25""","('월드 이탈리아 피사의 사탑', 3, '', '까이브', ""1'09'02""","('월드 이탈리아 피사의 사탑', 4, '', 'l지존지후l', ""1'09'49"")]",월드 이탈리아 피사의 사탑
2799,"까이브/100 : [('월드 두바이 다운타운', 1, '', 'YJWP', ""1'0...",까이브/100,"[('월드 두바이 다운타운', 1, '', 'YJWP', ""1'07'20""), ('...","[('월드 두바이 다운타운', 1, '', 'YJWP', ""1'07'20""","('월드 두바이 다운타운', 2, '스펙터 V1', '뱩소현', ""1'07'25""","('월드 두바이 다운타운', 3, '', '까이브', ""1'09'02""","('월드 두바이 다운타운', 4, '', 'l지존지후l', ""1'09'49"")]",월드 두바이 다운타운

In [10]:
for i in range(1,5):
  df[f'User_{i}_Rank'] = df[f'Match_User_{i}'].str.split(', ').str[1]
  df[f'User_{i}_Kart'] = df[f'Match_User_{i}'].str.split(', ').str[2]
  df[f'User_{i}_Name'] = df[f'Match_User_{i}'].str.split(', ').str[3]
  df[f'User_{i}_Time'] = df[f'Match_User_{i}'].str.split(', ').str[4]
df

,origin_dict,Match_Id,Match_Data,Match_User_1,Match_User_2,Match_User_3,Match_User_4,Track,User_1_Rank,User_1_Kart,...,User_2_Name,User_2_Time,User_3_Rank,User_3_Kart,User_3_Name,User_3_Time,User_4_Rank,User_4_Kart,User_4_Name,User_4_Time
0,"Color맥라렌/1 : [('차이나 라사', 1, '', 'Color맥라렌', ""1...",Color맥라렌/1,"[('차이나 라사', 1, '', 'Color맥라렌', ""1'50'03""), ('차...","[('차이나 라사', 1, '', 'Color맥라렌', ""1'50'03""","('차이나 라사', 2, '프로토 바이크 V1', 'KR퀵서비스', ""1'50'04""","('차이나 라사', 3, '나이트 세이버 V1', '하이럼스미스', ""1'50'66""","('차이나 라사', 4, '멘티스 X', 'Color옴팡이', ""1'51'98"")]",차이나 라사,1,'',...,'KR퀵서비스',"""1'50'04""",3,'나이트 세이버 V1','하이럼스미스',"""1'50'66""",4,'멘티스 X','Color옴팡이',"""1'51'98"")]"
1,"Color맥라렌/2 : [('네모 장난감 선물공장', 1, '', 'Color맥라렌...",Color맥라렌/2,"[('네모 장난감 선물공장', 1, '', 'Color맥라렌', ""1'50'03"")...","[('네모 장난감 선물공장', 1, '', 'Color맥라렌', ""1'50'03""","('네모 장난감 선물공장', 2, '프로토 바이크 V1', 'KR퀵서비스', ""1'...","('네모 장난감 선물공장', 3, '나이트 세이버 V1', '하이럼스미스', ""1'...","('네모 장난감 선물공장', 4, '멘티스 X', 'Color옴팡이', ""1'51'...",네모 장난감 선물공장,1,'',...,'KR퀵서비스',"""1'50'04""",3,'나이트 세이버 V1','하이럼스미스',"""1'50'66""",4,'멘티스 X','Color옴팡이',"""1'51'98"")]"
2,"Color맥라렌/3 : [('쥐라기 공룡 결투장', 1, '', 'Color맥라렌'...",Color맥라렌/3,"[('쥐라기 공룡 결투장', 1, '', 'Color맥라렌', ""1'50'03""),...","[('쥐라기 공룡 결투장', 1, '', 'Color맥라렌', ""1'50'03""","('쥐라기 공룡 결투장', 2, '프로토 바이크 V1', 'KR퀵서비스', ""1'5...","('쥐라기 공룡 결투장', 3, '나이트 세이버 V1', '하이럼스미스', ""1'5...","('쥐라기 공룡 결투장', 4, '멘티스 X', 'Color옴팡이', ""1'51'9...",쥐라기 공룡 결투장,1,'',...,'KR퀵서비스',"""1'50'04""",3,'나이트 세이버 V1','하이럼스미스',"""1'50'66""",4,'멘티스 X','Color옴팡이',"""1'51'98"")]"
3,"Color맥라렌/4 : [('차이나 라사', 1, '', 'Color맥라렌', ""1...",Color맥라렌/4,"[('차이나 라사', 1, '', 'Color맥라렌', ""1'50'03""), ('차...","[('차이나 라사', 1, '', 'Color맥라렌', ""1'50'03""","('차이나 라사', 2, '프로토 바이크 V1', 'KR퀵서비스', ""1'50'04""","('차이나 라사', 3, '나이트 세이버 V1', '하이럼스미스', ""1'50'66""","('차이나 라사', 4, '멘티스 X', 'Color옴팡이', ""1'51'98"")]",차이나 라사,1,'',...,'KR퀵서비스',"""1'50'04""",3,'나이트 세이버 V1','하이럼스미스',"""1'50'66""",4,'멘티스 X','Color옴팡이',"""1'51'98"")]"
4,"Color맥라렌/5 : [('메이플 헤네시스 공원', 1, '', 'Color맥라렌...",Color맥라렌/5,"[('메이플 헤네시스 공원', 1, '', 'Color맥라렌', ""1'50'03"")...","[('메이플 헤네시스 공원', 1, '', 'Color맥라렌', ""1'50'03""","('메이플 헤네시스 공원', 2, '프로토 바이크 V1', 'KR퀵서비스', ""1'...","('메이플 헤네시스 공원', 3, '나이트 세이버 V1', '하이럼스미스', ""1'...","('메이플 헤네시스 공원', 4, '멘티스 X', 'Color옴팡이', ""1'51'...",메이플 헤네시스 공원,1,'',...,'KR퀵서비스',"""1'50'04""",3,'나이트 세이버 V1','하이럼스미스',"""1'50'66""",4,'멘티스 X','Color옴팡이',"""1'51'98"")]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2795,"까이브/96 : [('노르테유 스카이웨이', 1, '', 'YJWP', ""1'07'...",까이브/96,"[('노르테유 스카이웨이', 1, '', 'YJWP', ""1'07'20""), ('노...","[('노르테유 스카이웨이', 1, '', 'YJWP', ""1'07'20""","('노르테유 스카이웨이', 2, '스펙터 V1', '뱩소현', ""1'07'25""","('노르테유 스카이웨이', 3, '', '까이브', ""1'09'02""","('노르테유 스카이웨이', 4, '', 'l지존지후l', ""1'09'49"")]",노르테유 스카이웨이,1,'',...,'뱩소현',"""1'07'25""",3,'','까이브',"""1'09'02""",4,'','l지존지후l',"""1'09'49"")]"
2796,"까이브/97 : [('WKC 코리아 서킷', 1, '', 'YJWP', ""1'07'...",까이브/97,"[('WKC 코리아 서킷', 1, '', 'YJWP', ""1'07'20""), ('W...","[('WKC 코리아 서킷', 1, '', 'YJWP', ""1'07'20""","('WKC 코리아 서킷', 2, '스펙터 V1', '뱩소현', ""1'07'25""","('WKC 코리아 서킷', 3, '', '까이브', ""1'09'02""","('WKC 코리아 서킷', 4, '', 'l지존지후l', ""1'09'49"")]",WKC 코리아 서킷,1,'',...,'뱩소현',"""1'07'25""",3,'','까이브',"""1'09'02""",4,'','l지존지후l',"""1'09'49"")]"
2797,"까이브/98 : [('메이플 리스항구 언덕길', 1, '', 'YJWP', ""1'0...",까이브/98,"[('메이플 리스항구 언덕길', 1, '', 'YJWP', ""1'07'20""), (...","[('메이플 리스항구 언덕길', 1, '', 'YJWP', ""1'07'20""","('메이플 리스항구 언덕길', 2, '스펙터 V1', '뱩소현', ""1'07'25""","('메이플 리스항구 언덕길', 3, '', '까이브', ""1'09'02""","('메이플 리스항구 언덕길', 4, '', 'l지존지후l', ""1'09'49"")]",메이플 리스항구 언덕길,1,'',...,'뱩소현',"""1'07'25""",3,'','까이브',"""1'09'02""",4,'','l지존지후l',"""1'09'49"")]"
2798,"까이브/99 : [('월드 이탈리아 피사의 사탑', 1, '', 'YJWP', ""1...",까이브/99,"[('월드 이탈리아 피사의 사탑', 1, '', 'YJWP', ""1'07'20""),...","[('월드 이탈리아 피사의 사탑', 1, '', 'YJWP', ""1'07'20""","('월드 이탈리아 피사의 사탑', 2, '스펙터 V1', '뱩소현', ""1'07'25""","('월드 이탈리아 피사의 사탑', 3, '', '까이브', ""1'09'02""","('월드 이탈리아 피사의 사탑', 4, '', 'l지존지후l', ""1'09'49"")]",월드 이탈리아 피사의 사탑,1,'',...,'뱩소현',"""1'07'25""",3,'','까이브',"""1'09'02""",4,'','l지존지후l',"""1'09'49"")]"
2799,"까이브/100 : [('월드 두바이 다운타운', 1, '', 'YJWP', ""1'0...",까이브/100,"[('월드 두바이 다운타운', 1, '', 'YJWP', ""1'07'20""), ('...","[('월드 두바이 다운타운', 1, '', 'YJWP', ""1'07'20""","('월드 두바이 다운타운', 2, '스펙터 V1', '뱩소현', ""1'07'25""","('월드 두바이 다운타운', 3, '', '까이브', ""1'09'02""","('월드 두바이 다운타운', 4, '', 'l지존지후l', ""1'09'49"")]",월드 두바이 다운타운,1,'',...,'뱩소현',"""1'07'25""",3,'','까이브',"""1'09'02""",4,'','l지존지후l',"""1'09'49"")]"

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2800 entries, 0 to 2799
Data columns (total 24 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   origin_dict   2800 non-null   object
 1   Match_Id      2800 non-null   object
 2   Match_Data    2800 non-null   object
 3   Match_User_1  2800 non-null   object
 4   Match_User_2  2800 non-null   object
 5   Match_User_3  2800 non-null   object
 6   Match_User_4  2800 non-null   object
 7   Track         2800 non-null   object
 8   User_1_Rank   2800 non-null   object
 9   User_1_Kart   2800 non-null   object
 10  User_1_Name   2800 non-null   object
 11  User_1_Time   2800 non-null   object
 12  User_2_Rank   2800 non-null   object
 13  User_2_Kart   2800 non-null   object
 14  User_2_Name   2800 non-null   object
 15  User_2_Time   2800 non-null   object
 16  User_3_Rank   2800 non-null   object
 17  User_3_Kart   2800 non-null   object
 18  User_3_Name   2800 non-null   object
 19  User_3_Time   2800 non-null   object
 20  User_4_Rank   2799 non-null   object
 21  User_4_Kart   2799 non-null   object
 22  User_4_Name   2799 non-null   object
 23  User_4_Time   2799 non-null   object
dtypes: object(24)
memory usage: 525.1+ KB

In [12]:
for i in range(1,5):
  df[f'User_{i}_Kart'] = df[f'User_{i}_Kart'].str.split('\'').str[1]
  df[f'User_{i}_Name'] = df[f'User_{i}_Name'].str.split('\'').str[1]
  df[f'User_{i}_Time'] = df[f'User_{i}_Time'].str.split('\"').str[1]
df

,origin_dict,Match_Id,Match_Data,Match_User_1,Match_User_2,Match_User_3,Match_User_4,Track,User_1_Rank,User_1_Kart,...,User_2_Name,User_2_Time,User_3_Rank,User_3_Kart,User_3_Name,User_3_Time,User_4_Rank,User_4_Kart,User_4_Name,User_4_Time
0,"Color맥라렌/1 : [('차이나 라사', 1, '', 'Color맥라렌', ""1...",Color맥라렌/1,"[('차이나 라사', 1, '', 'Color맥라렌', ""1'50'03""), ('차...","[('차이나 라사', 1, '', 'Color맥라렌', ""1'50'03""","('차이나 라사', 2, '프로토 바이크 V1', 'KR퀵서비스', ""1'50'04""","('차이나 라사', 3, '나이트 세이버 V1', '하이럼스미스', ""1'50'66""","('차이나 라사', 4, '멘티스 X', 'Color옴팡이', ""1'51'98"")]",차이나 라사,1,,...,KR퀵서비스,1'50'04,3,나이트 세이버 V1,하이럼스미스,1'50'66,4,멘티스 X,Color옴팡이,1'51'98
1,"Color맥라렌/2 : [('네모 장난감 선물공장', 1, '', 'Color맥라렌...",Color맥라렌/2,"[('네모 장난감 선물공장', 1, '', 'Color맥라렌', ""1'50'03"")...","[('네모 장난감 선물공장', 1, '', 'Color맥라렌', ""1'50'03""","('네모 장난감 선물공장', 2, '프로토 바이크 V1', 'KR퀵서비스', ""1'...","('네모 장난감 선물공장', 3, '나이트 세이버 V1', '하이럼스미스', ""1'...","('네모 장난감 선물공장', 4, '멘티스 X', 'Color옴팡이', ""1'51'...",네모 장난감 선물공장,1,,...,KR퀵서비스,1'50'04,3,나이트 세이버 V1,하이럼스미스,1'50'66,4,멘티스 X,Color옴팡이,1'51'98
2,"Color맥라렌/3 : [('쥐라기 공룡 결투장', 1, '', 'Color맥라렌'...",Color맥라렌/3,"[('쥐라기 공룡 결투장', 1, '', 'Color맥라렌', ""1'50'03""),...","[('쥐라기 공룡 결투장', 1, '', 'Color맥라렌', ""1'50'03""","('쥐라기 공룡 결투장', 2, '프로토 바이크 V1', 'KR퀵서비스', ""1'5...","('쥐라기 공룡 결투장', 3, '나이트 세이버 V1', '하이럼스미스', ""1'5...","('쥐라기 공룡 결투장', 4, '멘티스 X', 'Color옴팡이', ""1'51'9...",쥐라기 공룡 결투장,1,,...,KR퀵서비스,1'50'04,3,나이트 세이버 V1,하이럼스미스,1'50'66,4,멘티스 X,Color옴팡이,1'51'98
3,"Color맥라렌/4 : [('차이나 라사', 1, '', 'Color맥라렌', ""1...",Color맥라렌/4,"[('차이나 라사', 1, '', 'Color맥라렌', ""1'50'03""), ('차...","[('차이나 라사', 1, '', 'Color맥라렌', ""1'50'03""","('차이나 라사', 2, '프로토 바이크 V1', 'KR퀵서비스', ""1'50'04""","('차이나 라사', 3, '나이트 세이버 V1', '하이럼스미스', ""1'50'66""","('차이나 라사', 4, '멘티스 X', 'Color옴팡이', ""1'51'98"")]",차이나 라사,1,,...,KR퀵서비스,1'50'04,3,나이트 세이버 V1,하이럼스미스,1'50'66,4,멘티스 X,Color옴팡이,1'51'98
4,"Color맥라렌/5 : [('메이플 헤네시스 공원', 1, '', 'Color맥라렌...",Color맥라렌/5,"[('메이플 헤네시스 공원', 1, '', 'Color맥라렌', ""1'50'03"")...","[('메이플 헤네시스 공원', 1, '', 'Color맥라렌', ""1'50'03""","('메이플 헤네시스 공원', 2, '프로토 바이크 V1', 'KR퀵서비스', ""1'...","('메이플 헤네시스 공원', 3, '나이트 세이버 V1', '하이럼스미스', ""1'...","('메이플 헤네시스 공원', 4, '멘티스 X', 'Color옴팡이', ""1'51'...",메이플 헤네시스 공원,1,,...,KR퀵서비스,1'50'04,3,나이트 세이버 V1,하이럼스미스,1'50'66,4,멘티스 X,Color옴팡이,1'51'98
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2795,"까이브/96 : [('노르테유 스카이웨이', 1, '', 'YJWP', ""1'07'...",까이브/96,"[('노르테유 스카이웨이', 1, '', 'YJWP', ""1'07'20""), ('노...","[('노르테유 스카이웨이', 1, '', 'YJWP', ""1'07'20""","('노르테유 스카이웨이', 2, '스펙터 V1', '뱩소현', ""1'07'25""","('노르테유 스카이웨이', 3, '', '까이브', ""1'09'02""","('노르테유 스카이웨이', 4, '', 'l지존지후l', ""1'09'49"")]",노르테유 스카이웨이,1,,...,뱩소현,1'07'25,3,,까이브,1'09'02,4,,l지존지후l,1'09'49
2796,"까이브/97 : [('WKC 코리아 서킷', 1, '', 'YJWP', ""1'07'...",까이브/97,"[('WKC 코리아 서킷', 1, '', 'YJWP', ""1'07'20""), ('W...","[('WKC 코리아 서킷', 1, '', 'YJWP', ""1'07'20""","('WKC 코리아 서킷', 2, '스펙터 V1', '뱩소현', ""1'07'25""","('WKC 코리아 서킷', 3, '', '까이브', ""1'09'02""","('WKC 코리아 서킷', 4, '', 'l지존지후l', ""1'09'49"")]",WKC 코리아 서킷,1,,...,뱩소현,1'07'25,3,,까이브,1'09'02,4,,l지존지후l,1'09'49
2797,"까이브/98 : [('메이플 리스항구 언덕길', 1, '', 'YJWP', ""1'0...",까이브/98,"[('메이플 리스항구 언덕길', 1, '', 'YJWP', ""1'07'20""), (...","[('메이플 리스항구 언덕길', 1, '', 'YJWP', ""1'07'20""","('메이플 리스항구 언덕길', 2, '스펙터 V1', '뱩소현', ""1'07'25""","('메이플 리스항구 언덕길', 3, '', '까이브', ""1'09'02""","('메이플 리스항구 언덕길', 4, '', 'l지존지후l', ""1'09'49"")]",메이플 리스항구 언덕길,1,,...,뱩소현,1'07'25,3,,까이브,1'09'02,4,,l지존지후l,1'09'49
2798,"까이브/99 : [('월드 이탈리아 피사의 사탑', 1, '', 'YJWP', ""1...",까이브/99,"[('월드 이탈리아 피사의 사탑', 1, '', 'YJWP', ""1'07'20""),...","[('월드 이탈리아 피사의 사탑', 1, '', 'YJWP', ""1'07'20""","('월드 이탈리아 피사의 사탑', 2, '스펙터 V1', '뱩소현', ""1'07'25""","('월드 이탈리아 피사의 사탑', 3, '', '까이브', ""1'09'02""","('월드 이탈리아 피사의 사탑', 4, '', 'l지존지후l', ""1'09'49"")]",월드 이탈리아 피사의 사탑,1,,...,뱩소현,1'07'25,3,,까이브,1'09'02,4,,l지존지후l,1'09'49
2799,"까이브/100 : [('월드 두바이 다운타운', 1, '', 'YJWP', ""1'0...",까이브/100,"[('월드 두바이 다운타운', 1, '', 'YJWP', ""1'07'20""), ('...","[('월드 두바이 다운타운', 1, '', 'YJWP', ""1'07'20""","('월드 두바이 다운타운', 2, '스펙터 V1', '뱩소현', ""1'07'25""","('월드 두바이 다운타운', 3, '', '까이브', ""1'09'02""","('월드 두바이 다운타운', 4, '', 'l지존지후l', ""1'09'49"")]",월드 두바이 다운타운,1,,...,뱩소현,1'07'25,3,,까이브,1'09'02,4,,l지존지후l,1'09'49

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2800 entries, 0 to 2799
Data columns (total 24 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   origin_dict   2800 non-null   object
 1   Match_Id      2800 non-null   object
 2   Match_Data    2800 non-null   object
 3   Match_User_1  2800 non-null   object
 4   Match_User_2  2800 non-null   object
 5   Match_User_3  2800 non-null   object
 6   Match_User_4  2800 non-null   object
 7   Track         2800 non-null   object
 8   User_1_Rank   2800 non-null   object
 9   User_1_Kart   2800 non-null   object
 10  User_1_Name   2800 non-null   object
 11  User_1_Time   2100 non-null   object
 12  User_2_Rank   2800 non-null   object
 13  User_2_Kart   2800 non-null   object
 14  User_2_Name   2800 non-null   object
 15  User_2_Time   2600 non-null   object
 16  User_3_Rank   2800 non-null   object
 17  User_3_Kart   2800 non-null   object
 18  User_3_Name   2800 non-null   object
 19  User_3_Time   2800 non-null   object
 20  User_4_Rank   2799 non-null   object
 21  User_4_Kart   2799 non-null   object
 22  User_4_Name   2799 non-null   object
 23  User_4_Time   2599 non-null   object
dtypes: object(24)
memory usage: 525.1+ KB

In [14]:
df['User_4_Kart'][df['User_4_Kart'].isnull()]

200    NaN
Name: User_4_Kart, dtype: object

In [15]:
df.loc[200]#아마 1번 유저가 접속 오류 같은걸로 튕겨서 데이터가 없어서 앞으로 한칸씩 당겨진 걸로 보임

origin_dict     574335735623/1 : [('네모 장난감 선물공장', 2, '', '누군지1...
Match_Id                                           574335735623/1
Match_Data      [('네모 장난감 선물공장', 2, '', '누군지1', "1'13'58"), ('...
Match_User_1            [('네모 장난감 선물공장', 2, '', '누군지1', "1'13'58"
Match_User_2       ('네모 장난감 선물공장', 3, '', 'RedSunDISH', "1'16'19"
Match_User_3           ('네모 장난감 선물공장', 4, '', '금강청화', "1'20'26")]
Match_User_4                                                    0
Track                                                 네모 장난감 선물공장
User_1_Rank                                                     2
User_1_Kart
User_1_Name                                                  누군지1
User_1_Time                                               1'13'58
User_2_Rank                                                     3
User_2_Kart
User_2_Name                                            RedSunDISH
User_2_Time                                               1'16'19
User_3_Rank                                                     4
User_3_Kart
User_3_Name                                                  금강청화
User_3_Time                                               1'20'26
User_4_Rank                                                   NaN
User_4_Kart                                                   NaN
User_4_Name                                                   NaN
User_4_Time                                                   NaN
Name: 200, dtype: object

In [16]:
df['User_4_Time'][df['User_4_Time'].isnull()]# '-' 타임이 자연스럽게 걸러졌다 나중에 time nan은 Retire로 가자, 그리고 알수없는 맵이 있네... 이건 어쩐다

200     NaN
600     NaN
601     NaN
602     NaN
603     NaN
       ...
1195    NaN
1196    NaN
1197    NaN
1198    NaN
1199    NaN
Name: User_4_Time, Length: 201, dtype: object

In [31]:
df_tmp = df[['Match_Id']]
df_tmp = pd.concat([df_tmp, df.iloc[:,7:]], axis=1)
df_tmp

,Match_Id,Track,User_1_Rank,User_1_Kart,User_1_Name,User_1_Time,User_2_Rank,User_2_Kart,User_2_Name,User_2_Time,User_3_Rank,User_3_Kart,User_3_Name,User_3_Time,User_4_Rank,User_4_Kart,User_4_Name,User_4_Time
0,Color맥라렌/1,차이나 라사,1,,Color맥라렌,1'50'03,2,프로토 바이크 V1,KR퀵서비스,1'50'04,3,나이트 세이버 V1,하이럼스미스,1'50'66,4,멘티스 X,Color옴팡이,1'51'98
1,Color맥라렌/2,네모 장난감 선물공장,1,,Color맥라렌,1'50'03,2,프로토 바이크 V1,KR퀵서비스,1'50'04,3,나이트 세이버 V1,하이럼스미스,1'50'66,4,멘티스 X,Color옴팡이,1'51'98
2,Color맥라렌/3,쥐라기 공룡 결투장,1,,Color맥라렌,1'50'03,2,프로토 바이크 V1,KR퀵서비스,1'50'04,3,나이트 세이버 V1,하이럼스미스,1'50'66,4,멘티스 X,Color옴팡이,1'51'98
3,Color맥라렌/4,차이나 라사,1,,Color맥라렌,1'50'03,2,프로토 바이크 V1,KR퀵서비스,1'50'04,3,나이트 세이버 V1,하이럼스미스,1'50'66,4,멘티스 X,Color옴팡이,1'51'98
4,Color맥라렌/5,메이플 헤네시스 공원,1,,Color맥라렌,1'50'03,2,프로토 바이크 V1,KR퀵서비스,1'50'04,3,나이트 세이버 V1,하이럼스미스,1'50'66,4,멘티스 X,Color옴팡이,1'51'98
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2795,까이브/96,노르테유 스카이웨이,1,,YJWP,1'07'20,2,스펙터 V1,뱩소현,1'07'25,3,,까이브,1'09'02,4,,l지존지후l,1'09'49
2796,까이브/97,WKC 코리아 서킷,1,,YJWP,1'07'20,2,스펙터 V1,뱩소현,1'07'25,3,,까이브,1'09'02,4,,l지존지후l,1'09'49
2797,까이브/98,메이플 리스항구 언덕길,1,,YJWP,1'07'20,2,스펙터 V1,뱩소현,1'07'25,3,,까이브,1'09'02,4,,l지존지후l,1'09'49
2798,까이브/99,월드 이탈리아 피사의 사탑,1,,YJWP,1'07'20,2,스펙터 V1,뱩소현,1'07'25,3,,까이브,1'09'02,4,,l지존지후l,1'09'49
2799,까이브/100,월드 두바이 다운타운,1,,YJWP,1'07'20,2,스펙터 V1,뱩소현,1'07'25,3,,까이브,1'09'02,4,,l지존지후l,1'09'49

이제 어느정도 정리는 좀 됐는데, 중간 중간에 비어있는 값이나 데이터 타입 같은 걸 좀 바꾸는게 좋을 듯?

In [32]:
df_tmp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2800 entries, 0 to 2799
Data columns (total 18 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Match_Id     2800 non-null   object
 1   Track        2800 non-null   object
 2   User_1_Rank  2800 non-null   object
 3   User_1_Kart  2800 non-null   object
 4   User_1_Name  2800 non-null   object
 5   User_1_Time  2100 non-null   object
 6   User_2_Rank  2800 non-null   object
 7   User_2_Kart  2800 non-null   object
 8   User_2_Name  2800 non-null   object
 9   User_2_Time  2600 non-null   object
 10  User_3_Rank  2800 non-null   object
 11  User_3_Kart  2800 non-null   object
 12  User_3_Name  2800 non-null   object
 13  User_3_Time  2800 non-null   object
 14  User_4_Rank  2799 non-null   object
 15  User_4_Kart  2799 non-null   object
 16  User_4_Name  2799 non-null   object
 17  User_4_Time  2599 non-null   object
dtypes: object(18)
memory usage: 393.9+ KB

In [33]:
df_tmp.to_csv('preprocessed_data.csv', index=False)